version: "3.9"

services:
  bot:
    build: .
    container_name: bot-moderator
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
    restart: unless-stopped
